-- AlterTable
ALTER TABLE "Admin" ALTER COLUMN "id" SET DEFAULT LPAD((FLOOR(RANDOM() * 100000000))::TEXT, 8, '0');

-- AlterTable
ALTER TABLE "Category" ALTER COLUMN "id" SET DEFAULT LPAD((FLOOR(RANDOM() * 100000000))::TEXT, 8, '0');

-- AlterTable
ALTER TABLE "Exam" ALTER COLUMN "id" SET DEFAULT LPAD((FLOOR(RANDOM() * 100000000))::TEXT, 8, '0');

-- AlterTable
ALTER TABLE "Option" ALTER COLUMN "id" SET DEFAULT LPAD((FLOOR(RANDOM() * 100000000))::TEXT, 8, '0');

-- AlterTable
ALTER TABLE "Question" ALTER COLUMN "id" SET DEFAULT LPAD((FLOOR(RANDOM() * 100000000))::TEXT, 8, '0');

-- AlterTable
ALTER TABLE "Response" ALTER COLUMN "id" SET DEFAULT LPAD((FLOOR(RANDOM() * 100000000))::TEXT, 8, '0');

-- AlterTable
ALTER TABLE "Result" ALTER COLUMN "id" SET DEFAULT LPAD((FLOOR(RANDOM() * 100000000))::TEXT, 8, '0');

-- AlterTable
ALTER TABLE "Topic" ALTER COLUMN "id" SET DEFAULT LPAD((FLOOR(RANDOM() * 100000000))::TEXT, 8, '0');

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "id" SET DEFAULT LPAD((FLOOR(RANDOM() * 100000000))::TEXT, 8, '0');
